### ISSUE TITLE
ImportError: cannot import name 'TextScoreEncoder' from 'modeling.modeling_encoder'

### ISSUE THREAD

**Issue by chuangdang-vue** [RUCAIBox/SAFE#1]
Traceback (most recent call last):
  File "/home/byh452/SAFE/utils/conceptnet.py", line 10, in <module>
    from .other_utils import check_file
  File "/home/byh452/SAFE/utils/other_utils.py", line 15, in <module>
    from modeling.modeling_qagnn import LM_QAGNN, LM_QAGNN_PCA_Decouple,LM_QAGNN_DataLoader,SAFE,LM_GNN_MetaPathOneHot_DataLoader, LM_QAGNN_Analysis
  File "/home/byh452/SAFE/modeling/modeling_qagnn.py", line 6, in <module>
    from modeling.modeling_encoder import TextEncoder, TextScoreEncoder, MODEL_NAME_TO_CLASS, TextPromptEncoder, \
ImportError: cannot import name 'TextScoreEncoder' from 'modeling.modeling_encoder'

**Comment by JBoRu** [comment]
I have fixed this bug, thanks!
